Help page init, Problem component init.
padavancrew/tutorrarium pull request #12
Opened 2017-03-03 15:32 UTC by Edgar000

2017-03-03 22:27 UTC, ShevchukJulia requested changes

2017-03-03 22:27 UTC, ShevchukJulia commented on client/containers/problems_database.js
> +        description: 'How can I ng-repeat in React?',
You already did that using simple items.map(item => <ItemComponent item={item}/>)

2017-03-03 22:27 UTC, ShevchukJulia commented on client/containers/App.js
> +                    <Route path="help" component={() => (<Help problems={problemsData}/>)}/>
You definitely should use connect for this component to pass data from redux store into your Help component.
You should use examples from specification: 
https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options


In my opinion, for better decomposition you should create ProblemList component and wrap into react-redux connect component. And keep Home component simple and isolated from store.
For more information about architecture decomposition read: 
https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.odxxhoo1t

2017-03-04 16:33 UTC, Edgar000 commented on client/containers/problems_database.js
> +        description: 'How can I ng-repeat in React?',
i know it!

2017-03-04 16:41 UTC, Edgar000 commented on client/containers/App.js
> +                    <Route path="help" component={() => (<Help problems={problemsData}/>)}/>
w i p

2017-03-10 11:41 UTC, ShevchukJulia approved these changes

2017-03-10 11:43 UTC, ShevchukJulia approved these changes
ok)

2017-03-10 12:00 UTC, OleksiiKukuruza approved these changes

2017-03-10 12:00 UTC, OleksiiKukuruza commented on client/components/Help/Help.js
> +        //fetch
next time if you want to add todo - add comment in format: // TODO: some stuff

2017-03-10 12:00 UTC, OleksiiKukuruza commented on client/components/Problem/Problem.js
> +        const isAnswered = (
name this correctly please

2017-03-10 12:00 UTC, OleksiiKukuruza commented on client/components/Problem/Problem.scss
> +  i {
As I said before - if you need style something - add class on that node. Avoid css selectors nesting

2017-03-10 12:00 UTC, OleksiiKukuruza commented on client/components/Problem/Problem.scss
> +  i {
same

2017-03-10 12:00 UTC, OleksiiKukuruza commented on client/components/Problem/Problem.scss
> +  .answered {
same

2017-03-10 12:00 UTC, OleksiiKukuruza commented on client/components/Problem/Problem.scss
> +  .not-answered {
same

2017-03-10 12:00 UTC, OleksiiKukuruza commented on client/components/Problem/Problem.scss
> +  i{
same

2017-03-10 12:00 UTC, merged