PseudoCod
padavancrew/tutorrarium pull request #13
Opened 2017-03-04 15:02 UTC by Oleksandr3008

2017-03-04 16:40 UTC, Edgar000 commented on client/components/Header.js
> +import './Header.scss';
And where is this scss file?

2017-03-05 14:34 UTC, OleksiiKukuruza requested changes

2017-03-05 14:34 UTC, OleksiiKukuruza commented on client/components/Header.js
> +                <div className="header-navButton">Home </div>
Correct indentations

2017-03-05 14:34 UTC, OleksiiKukuruza commented on client/components/Header.js
> +                <div className="header-navButton">Home </div>
And remove spaces if this is not real spaces. If you need margin - use margin.

2017-03-05 17:59 UTC, closed without merging